python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Psze_l Higgsstd.steer 0 Psze_l0mu
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Psze_l Higgsstd.steer 0 Psze_l0tau
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Psznu_l Higgsstd.steer 0 Psznu_l0mumu
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pww_l Higgsstd.steer 0 Pww_l0ll
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pww_sl Higgsstd.steer 0 Pww_sl0muq
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pww_sl Higgsstd.steer 0 Pww_sl0tauq
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_l Higgsstd.steer 0 Pzz_l04mu
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_l Higgsstd.steer 0 Pzz_l04tau
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_l Higgsstd.steer 0 Pzz_l0mumu
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_l Higgsstd.steer 0 Pzz_l0taumu
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_l Higgsstd.steer 0 Pzz_l0tautau
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzzorww_l Higgsstd.steer 0 Pzzorww_l0mumu
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzzorww_l Higgsstd.steer 0 Pzzorww_l0tautau
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_sl Higgsstd.steer 0 Pzz_sl0mu_down
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_sl Higgsstd.steer 0 Pzz_sl0mu_up
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_sl Higgsstd.steer 0 Pzz_sl0tau_down
python pyinput.py /cefs/higgs/cuizw/flass/zexhuu/rec/Pzz_sl Higgsstd.steer 0 Pzz_sl0tau_up